// <auto-generated />
using System;
using CarsShop.DAL.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarsShop.DAL.Migrations
{
    [DbContext(typeof(UserContext))]
    [Migration("20221008091410_CarsShopDB")]
    partial class CarsShopDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CarsShop.DAL.Entities.Car", b =>
                {
                    b.Property<int>("CarID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CarID"), 1L, 1);

                    b.Property<string>("CarModel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Desc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Img")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("CarID");

                    b.HasIndex("UserID");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            CarID = 11,
                            CarModel = "Tesla",
                            Desc = "Electic",
                            Img = "/img/Tesla.png",
                            Price = 23000,
                            UserID = 1
                        },
                        new
                        {
                            CarID = 12,
                            CarModel = "Citroen C4 II",
                            Desc = "Fuel",
                            Img = "/img/Citroen.png",
                            Price = 6800,
                            UserID = 2
                        },
                        new
                        {
                            CarID = 13,
                            CarModel = "Toyota Yaris",
                            Desc = "Fuel",
                            Img = "/img/Yaris.jpg",
                            Price = 5400,
                            UserID = 2
                        },
                        new
                        {
                            CarID = 14,
                            CarModel = "BMW I3",
                            Desc = "Electic",
                            Img = "/img/BMW.png",
                            Price = 16000,
                            UserID = 3
                        },
                        new
                        {
                            CarID = 15,
                            CarModel = "Wolkswagen Polo",
                            Desc = "Fuel",
                            Img = "/img/Polo.jpg",
                            Price = 9800,
                            UserID = 1
                        });
                });

            modelBuilder.Entity("CarsShop.DAL.Entities.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"), 1L, 1);

                    b.Property<DateTime>("UserBirthday")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserRole")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserID");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserID = 1,
                            UserBirthday = new DateTime(2005, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserName = "UserName1",
                            UserPassword = "3453sdfd",
                            UserRole = "User"
                        },
                        new
                        {
                            UserID = 2,
                            UserBirthday = new DateTime(1996, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserName = "UserName2",
                            UserPassword = "435dfgrfgt",
                            UserRole = "User"
                        },
                        new
                        {
                            UserID = 3,
                            UserBirthday = new DateTime(1987, 2, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserName = "UserName3",
                            UserPassword = "48efge65",
                            UserRole = "User"
                        });
                });

            modelBuilder.Entity("CarsShop.DAL.Entities.Car", b =>
                {
                    b.HasOne("CarsShop.DAL.Entities.User", "User")
                        .WithMany("Cars")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CarsShop.DAL.Entities.User", b =>
                {
                    b.Navigation("Cars");
                });
#pragma warning restore 612, 618
        }
    }
}
